name: Otus final project tests

on:
  push:
    branches:
      - main
      - final*

env:
  GO111MODULE: "on"

jobs:
  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: make lint
        run: make lint
        working-directory: /home/runner/work/image_previewer/image_previewer

      - name: make build
        run: make build
        working-directory: /home/runner/work/image_previewer/image_previewer

      - name: make test
        run: make test
        working-directory: /home/runner/work/image_previewer/image_previewer

      - name: make integration test
        run: make integration_test
        working-directory: /home/runner/work/image_previewer/image_previewer
      